### ISSUE TITLE
Why no Repost?

### ISSUE THREAD

**Issue by HasturTime** [NicolasConstant/BirdsiteLive#123] opened 2021-11-02 12:59 UTC
I use https://birdsite.slashdev.space/ to get some favourite Twitter accounts into my pleroma feed. 

It works well enough, but why can't I repost the tweets, so I can share them with my followers on the pleroma instance?

**Comment by NicolasConstant** [comment] 2021-11-02 16:03
duplicate of #35

**Closed by NicolasConstant** 2021-11-02 16:03 UTC
