### ISSUE TITLE
extra @

### ISSUE THREAD

**Issue by xsuchy** [NicolasConstant/BirdsiteLive#30] opened 2021-01-07 15:26 UTC
Search for handle produce extra @

Reproducer:
1. search for @michalblaha
2. you got suggested to follow https://beta.birdsite.live/users/@michalblaha (that URL is correct), but on the content of the page is:
    @@michalblaha@beta.birdsite.live
  There is extra @ and it appears twice on page

**Comment by NicolasConstant** [comment] 2021-01-07 15:51
thanks for your contribution 🙂
it's a duplicate of #28 but since you provided a better description of the issues lets keep them both.

**Closed** 2021-01-07 18:38 UTC
